name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master   # run pipeline on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 13.230.26.195
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/Laracoffee

            # Make sure git allows this directory
            sudo git config --global --add safe.directory /var/www/Laracoffee

            # Pull latest code
            sudo git pull origin master

            # Install dependencies
            sudo composer install --no-dev --prefer-dist --optimize-autoloader

            sudo npm install

            # Run migrations
            sudo php artisan migrate --force
            php artisan storage:link


            # Fix permissions
            sudo chown -R www-data:www-data /var/www/Laracoffee
            sudo chmod -R 775 /var/www/Laracoffee/storage /var/www/Laracoffee/bootstrap/cache

            # Rebuild Laravel caches
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache

            # Restart services
            sudo systemctl restart php8.3-fpm
            sudo systemctl reload nginx
